/** Writes the PerpsEngine ABI as a typed constant. Run after `forge build` in packages/contracts. */
const artifact = new URL(
  "../../../contracts/out/PerpsEngine.sol/PerpsEngine.json",
  import.meta.url,
);
const target = new URL("../src/generated/abi.ts", import.meta.url);

export async function renderAbi(): Promise<string> {
  const { abi } = (await Bun.file(artifact).json()) as { abi: unknown[] };
  return [
    "// Generated by scripts/generate-abi.ts from packages/contracts. Do not edit.",
    `export const perpsEngineAbi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  await Bun.write(target, await renderAbi());
  console.info(`Wrote ${target.pathname}`);
}
